FLASK_APP='manage.py'
FLASK_ENV=development
SECRET_KEY='*\xd8uM9+}4<Z\n\xfc\x84\xb5\x06\xbez]\x83>2\x9eq\x98'
DB_USERNAME=forum_user
DB_PASSWORD=forum_password
DB_HOST=localhost
DATABASE_NAME=forum
MYSQL_ROOT_PASSWORD=34times34
BLOG_NAME='OTUS Blog'
BLOG_POST_IMAGES_PATH='/root/WorkPython/Flask/otus_project/static/images/uploads'
